# Generated by Django 5.2.8 on 2025-11-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0002_genre_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
