# Generated by Django 5.2.8 on 2025-11-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0004_alter_author_bio_alter_author_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='image',
        ),
        migrations.AddField(
            model_name='author',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
