# Generated by Django 5.2.8 on 2025-11-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0005_remove_author_image_author_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_books/'),
        ),
    ]
